### ISSUE TITLE
Bot doesn't post info on new files

### ISSUE THREAD

**Issue by ROMVoid95** [ErdbeerbaerLP/Curseforge-Bot#1]
dont know if its due to the new curseforge links, also does this work with modpacks too?

**Comment by ErdbeerbaerLP** [comment]
For me it works, might need to wait a little.
It should work with any curseforge project

**Comment by ROMVoid95** [comment]
does it have to be a release? or does it also accept Beta and Alpha?

**Comment by ErdbeerbaerLP** [comment]
It accepts everything it can see on the curseforge page

**Comment by ROMVoid95** [comment]
okay it posted only after the bot was restarted

**Comment by ErdbeerbaerLP** [comment]
ok, sounds like my attempt on clearing the curseforge cache did not work

**Comment by ROMVoid95** [comment]
sounds good, love the idea of the bot btw, will really help my modpack discord

**Comment by ErdbeerbaerLP** [comment]
Check if you have the latest version, if you have, can you try if it still happens with this version: http://erdbeerbaerapi.tk/Curseforge-Bot-1.0.5.jar ?

**Comment by ROMVoid95** [comment]
tried with that version, uploaded a beta file for project, can confirm it only updates channel after bot is restarted and files were approved before bot restart.

i waited a little while, is there a range time it needs to wait if bot is live?

**Comment by ErdbeerbaerLP** [comment]
I would say it shouldn´t take longer than 2 hours. (It might be that curseforge itself is caching a little bit)

**Comment by ROMVoid95** [comment]
okay i'll try it again and wait, i didnt wait that long. i'm not too familiar with caching, i just assumed (without looking at the code) it was a async task that checked the api and looked for different version numbers. unless it is and i go look and see that, in that case. Apologies for the issues lol

**Comment by ErdbeerbaerLP** [comment]
If you want you can try the new version. It works with the new curseforge layout

**Comment by ROMVoid95** [comment]
works like a charm my friend!
