### ISSUE TITLE
Bot Port?

### ISSUE THREAD

**Issue by Tim-Rambo** [ErdbeerbaerLP/Curseforge-Bot#19]
Does the bot use any spesific port?
I need a port to be able to set it up on peterodactyl game panel :) 

Kind Regards
TimRambo

**Comment by ErdbeerbaerLP** [comment]
No, the bot does not require any open port, as it does not accept any incoming connections. 
It only needs to communicate with https://discord.com/api/ , https://curseforge.com and maybe with github, depending on configuration.
