### ISSUE TITLE
Help Locating Files

### ISSUE THREAD

**Issue by OptiSar** [ErdbeerbaerLP/Curseforge-Bot#45]
Where do i find the jar file that I need to execute I've found the config files but can not locate the jar file could you help please?

**Comment by ErdbeerbaerLP** [comment]
https://github.com/ErdbeerbaerLP/Curseforge-Bot/releases

Get the jar there.

Config file will be generated after first launch.
I recommend executing it from command line so you get log output (java -jar jarfile.jar )
