### ISSUE TITLE
GitHub integration hardcoded to `master` branch

### ISSUE THREAD

**Issue by HandyHat** [ErdbeerbaerLP/Curseforge-Bot#53]
When placing the cache file in a GitHub repo, the bot looks for the `master` branch. However if you are using an already created repo, the default branch might be `main` instead, which means the bot fails to create the cache file.

**Comment by ErdbeerbaerLP** [comment]
Will Not be changed anymore as an rewrite is in progress, making self-hosting no longer an requirement, as the bot will be hosted on an server then, only requiring an invite and some command usage
