### ISSUE TITLE
Non fixed Curse API version

### ISSUE THREAD

**Issue by lineargraph** [ErdbeerbaerLP/Curseforge-Bot#8]
Currently the Curse API is fixed to the MASTER of https://github.com/TheRandomLabs/CurseAPI, which can update at any time with a breaking change, and cause this build to be nonreproducible. I'd recommend fixing to a certain tag or commit for reproducible builds.

**Comment by ErdbeerbaerLP** [comment]
Not possible at the moment, as all jitpack builds using commits fail
![image](https://user-images.githubusercontent.com/27149563/90313510-72b11c00-df0d-11ea-9379-1008e3d5dbbf.png)

**Comment by lineargraph** [comment]
I think `f93356af62` should work, but im not entirely sure. But thanks for looking into it regardless.
